program igs_out
	external idataline
	character*80 char,filename
	real,allocatable:: xyz(:,:,:,:)
	real,allocatable:: xknot(:)
	integer,allocatable::nijk(:,:)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	write(*,*)'This program converts Plot3d Surface Grid file to IGES file.'
	write(*,*)'The surface type is Rational B-Spline surface.'
	write(*,*)'Email: zhangyufei@tsinghua.edu.cn'
	write(*,*)
	write(*,*)'Input  file: IGS.grd'
	write(*,*)'Output file: IGS.igs'
	write(*,*)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!	读入计数文件
	itype=128

	filename='igs.grd'
	open(51,file=filename,status='old',action='read',err=1001)
	read(51,*)iblock
	allocate(nijk(iblock,5))
	nijk=0
	read(51,*)((nijk(i,ii),ii=1,3),i=1,iblock)
	do i=1,iblock
		if(nijk(i,3).ne.1)then
			write(*,*)'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
			write(*,*)'Wrong Input file: Dimension K is not 1.'
			write(*,*)'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
			stop
		endif
		if(nijk(i,1).lt.4 .or. nijk(i,2).lt.4)then
		    write(*,*)'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
			write(*,*)'Wrong Input file: Dimension I or J less than 4.'
			write(*,*)'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
			stop
		endif
		ni=nijk(i,1)
		nj=nijk(i,2)
		nijk(i,4)=idataline(ni,nj)
	end do
	nijk(1,5)=1
	do i=2,iblock
		nijk(i,5)=nijk(i-1,4)+nijk(i-1,5)
	end do

!	do i=1,iblock
!	write(*,'(5i8)')nijk(i,1:5)
!	end do
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	open(5,file='igs.igs')
!	 录入开始段
	write(5,'(A80)')'This is igs file generated by ZHANG Yufei. All rights reserved.         S      1'
!	 录入全局段
	write(5,'(A80)')'1H,,1H;,14HZHANGYUFEI.igs,,ZHANG1.0,ZHANG1.0,32,38,6,308,               G      1'
	write(5,'(A80)')'15,,1.0,2,2HMM,16,0.096,15H20111111.111111,0.0001,10000.0,10HZHANGYufei,G      2'
	write(5,'(A80)')'8HTsinghua,11,0,15H20111111.111111,;                                    G      3'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!	 录入索引段	
do ib = 1,iblock
	nk=nijk(ib,3)
	ni=nijk(ib,1)
	nj=nijk(ib,2)
	istartline=nijk(ib,5)
	iendline=nijk(ib,4)

	write(5,125)itype,istartline,0,0,0,0,0,0,0,0,0,0,'D',ib*2-1
	write(5,126)itype,0,0,iendline,0,'BSp Surf',0,'D',ib*2
125 format(8i8,4i2,A1,i7)
126 format(5i8,A24,i8,A1,i7)
end do 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!	 录入数据段
iline=0
do ib = 1,iblock
	nk=nijk(ib,3)
	ni=nijk(ib,1)
	nj=nijk(ib,2)
	iline=iline+1
	write(5,'(10(i5,","),i12,A1,i7)')itype,ni-1,nj-1,3,3,0,0,1,0,0,ib*2-1,'P',iline
!	 录入节点矢量	
	allocate(xknot(-3:ni))
	call knotx(ni,xknot)
	do ix=-3,ni
		iline=iline+1
		write(5,'(e19.10,",",i52,A1,i7)')xknot(ix),ib*2-1,'P',iline
	end do
	ximin=xknot(-3)
	ximax=xknot(ni)
	deallocate(xknot)
	
	allocate(xknot(-3:nj))
	call knotx(nj,xknot)
	do ix=-3,nj
		iline=iline+1
		write(5,'(e19.10,",",i52,A1,i7)')xknot(ix),ib*2-1,'P',iline
	end do
	xjmin=xknot(-3)
	xjmax=xknot(nj)
	deallocate(xknot)
!	录入各点权值
	do j=1,nj
		do i=1,ni
			iline=iline+1
			write(5,'(e19.10,",",i52,A1,i7)')1.0,ib*2-1,'P',iline
		end do
	end do
!	录入各点坐标
	allocate(xyz(ni,nj,nk,3))
	read(51,*,err=1002)((((xyz(i,j,k,ii),i=1,ni),j=1,nj),k=1,nk),ii=1,3)
	do k=1,nk
	do j=1,nj
		do i=1,ni
			iline=iline+1
			write(5,'(3(e19.10,","),i12,A1,i7)')xyz(i,j,k,1:3),ib*2-1,'P',iline
		end do
	end do
	end do
	deallocate(xyz)
!	录入参数方向的起始和结尾
	iline=iline+1
	write(5,'(3(e14.6,","),e14.6,";",i12,A1,i7)')ximin,ximax,xjmin,xjmax,ib*2-1,'P',iline

end do
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!	录入结束段
	write(5,'(4(A1,i7),A41,i7)')'S',1,'G',3,'D',2*iblock,'P',iline,'T',1

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	close(51);close(5)
	write(*,*)'Convertion Completed!'
		stop
1001	continue
		write(*,*)'!!!!!!!!!!!!!!!!!'
		write(*,*)'Input file error!'
		write(*,*)'!!!!!!!!!!!!!!!!!'
		stop
1002	continue
		write(*,*)'!!!!!!!!!!!!!!!!!!'
		write(*,*)'Coordinates error!'
		write(*,*)'!!!!!!!!!!!!!!!!!!'
		stop
end program

subroutine knotx(ni,xknot)
	real xknot(-3:ni)
	do i=-3,0
		xknot(i)=0.0
	end do

	do i=ni-3,ni
		xknot(i)=1.0
	end do

	do i=1,ni-3
		xknot(i)=xknot(ni)*float(i)/float(ni-3)
	end do
	return
end subroutine

function idataline(ni,nj)
	integer ni,nj
	i1=ni+4
	i2=nj+4
	i3=ni*nj
	i4=ni*nj
	i5=1+1
	idataline=i1+i2+i3+i4+i5
end function